# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Matrix Product in RcppArmadillo.
#'
#' @param m numeric matrix
#' @param m2 numeric matrix
#' @return matrix product of m and m2
#' @export
arma_mm <- function(m, m2) {
    .Call('_MATS_arma_mm', PACKAGE = 'MATS', m, m2)
}

#' Matrix Inversion in RcppArmadillo.
#'
#' @param Am numeric matrix
#' @return Inversion of Am
#' @export
solve_mm <- function(Am) {
    .Call('_MATS_flowCalcCpp', PACKAGE = 'MATS', Am)
}

